### ISSUE TITLE
xfsettingsd crashes while logging

### ISSUE THREAD

**Issue by aakeene** [advzhangyang/xfce-xfsettingsd#1]
Several ways I've been able to crash xfsettingd reliably, which causes my linux mint session to log me out.   1. When running Spotify, open a Chrome browser window.   2. Occasionally when opening Thunderbird email.

I am running linux mint 21.3, but was seeing it with the previous version.   Note that using the "System Reports" tool allowed me to collect the crash information, but would not open a valid web page for  a bug tracker.   I am running XFCE.

Pastebin log at:  https://termbin.com/5tp6
[crash.tar.gz](https://github.com/advzhangyang/xfce-xfsettingsd/files/13942402/crash.tar.gz)

**Comment by aakeene** [comment]
===================================================================
 Info                                                              
===================================================================
           PID: 159380 (xfsettingsd)
           UID: 1000 (angelo)
           GID: 1000 (angelo)
        Signal: 5 (TRAP)
     Timestamp: Mon 2024-01-15 11:55:57 MST (23min ago)
  Command Line: xfsettingsd --display :0.0 --sm-client-id 2eb19bff7-6862-4932-b375-c24234be40e3
    Executable: /usr/bin/xfsettingsd
 Control Group: /user.slice/user-1000.slice/session-c9.scope
          Unit: session-c9.scope
         Slice: user-1000.slice
       Session: c9
     Owner UID: 1000 (angelo)
       Boot ID: 984f3f8bc7454e64861c2e9115b3e19b
    Machine ID: 0a2058fc54c649ada1c67c1b7f870152
      Hostname: frost
       Storage: /var/lib/systemd/coredump/core.xfsettingsd.1000.984f3f8bc7454e64861c2e9115b3e19b.159380.1705344957000000.zst (present)
     Disk Size: 437.8K
       Message: Process 159380 (xfsettingsd) of user 1000 dumped core.
                
                Found module linux-vdso.so.1 with build-id: 4f896783a5130f862bd0619fa1f4ac5221cd1a70
                Found module libappmenu-gtk3-parser.so.0 with build-id: 577c31c5ef76dfe99de9239fa5a0651417572b6b
                Found module libappmenu-gtk-module.so with build-id: a48d1471a7036b6cd4cddafc335964be370cc296
                Found module libgnomekbd.so.8 with build-id: 636c4ae86d1bff2aa2cb92b39b42e41ff714ec7c
                Found module libgnomekbdui.so.8 with build-id: e01ea8bdf45e3995a2449f1cb4bd8e6bd886efa5
                Found module libxapp.so.1 with build-id: 2edf20e3d0050c0e5e1d27af3fee61b11ae84f5e
                Found module libxapp-gtk3-module.so with build-id: 42e91d0b54421ed6a3ef8be0b9060c76207dd4e2
                Found module libgpg-error.so.0 with build-id: 3fbec71c67bee60d8aef00697ee187079b0fb307
                Found module libgcrypt.so.20 with build-id: 60a5e524de0ed8323edf33e9eb9127a9eee02359
                Found module libcap.so.2 with build-id: b4bf900abf14aabe12d90988ceb30888acb2bcb0
                Found module liblz4.so.1 with build-id: a85971851cd059f1af80d553c8e7170d42ec59a1
                Found module libzstd.so.1 with build-id: 5d9d0d946a3154a748e87e17af9d14764519237b
                Found module libdatrie.so.1 with build-id: 128b6874a47f2b783d9e9060d3caaee4110bfd3d
                Found module libsystemd.so.0 with build-id: e7268ae5d5222eb3c780756d071132ac49467d0b
                Found module libbrotlicommon.so.1 with build-id: 43a72967cf84155914c8b3e915926733d1e57c11
                Found module libgcc_s.so.1 with build-id: e3a44e0da9c6e835d293ed8fd2882b4c4a87130c
                Found module libstdc++.so.6 with build-id: e37fe1a879783838de78cbc8c80621fa685d58a2
                Found module libicudata.so.70 with build-id: b1c2496dd0543023c7a19c961bb7f3abc818f465
                Found module libmd.so.0 with build-id: cd2d2f71b3967ebde30e2aa43b8eb63339020c06
                Found module libXdmcp.so.6 with build-id: 6b60f99504aa1d3999ea02a14366d1a39d6c5dcf
                Found module libXau.so.6 with build-id: 7089b383cacbfc1760634a3be19a923e51fe3315
                Found module libpcre2-8.so.0 with build-id: 184a841c55fb7fe5e3873fcda8368c71016cd54c
                Found module libblkid.so.1 with build-id: cdf95a964e3302bb356fefc4b801fae8c4340b31
                Found module libgraphite2.so.3 with build-id: 5ffbc76fc948f6b88d766a7210c2e6a329a6c278
                Found module libthai.so.0 with build-id: afa54530349e68380815d606d15dbfda8952799f
                Found module libatspi.so.0 with build-id: 2843c68233d5ba81da3d6bc31422e49472873dba
                Found module libdbus-1.so.3 with build-id: 63e8b99215502138cb63afd6d65851a5e837ed49
                Found module libxcb-render.so.0 with build-id: cb521131fd3b0f2ee6056cbc2014b3b8ef0d5c0e
                Found module libxcb-shm.so.0 with build-id: edb24ef4079aa423edcc50a3bb0dfb912fe8a57a
                Found module libpixman-1.so.0 with build-id: 5e936cdac032b6048d9d1a8c0bb0e4a10c86d48c
                Found module libbrotlidec.so.1 with build-id: 4b1f390dd6e24d49684db8b2443d082379e8e977
                Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265
                Found module libicuuc.so.70 with build-id: bef3ff1d70aadd68aab07d858a759360c8b919ae
                Found module libX11-xcb.so.1 with build-id: 70f2a36d79c623f42fd70fa7ffb06d8877c74f16
                Found module libxcb-util.so.1 with build-id: 898a03cabe0d55491c4bf447c7399b8bf4e392d8
                Found module libbsd.so.0 with build-id: 9a6c72469251e2feb63e175ef5cb944ce6e00df3
                Found module libjpeg.so.8 with build-id: c54abff9294357e28532a76a049a4cb2542fc15b
                Found module libpng16.so.16 with build-id: d58bf7c11ac793d528926238d831792b5ef792cf
                Found module ld-linux-x86-64.so.2 with build-id: 15921ea631d9f36502d20459c43e5c85b7d6ab76
                Found module libpcre.so.3 with build-id: 3982f316c887e3ad9598015fa5bae8557320476a
                Found module libffi.so.8 with build-id: 59c2a6b204f74f358ca7711d2dfd349d88711f6a
                Found module libXrender.so.1 with build-id: 7ccbfa4c24e93c42fa50dd2e42fa277630f9650c
                Found module libxcb.so.1 with build-id: 1bef862a339557aa16c34c7a4b27f8f3aea90517
                Found module libselinux.so.1 with build-id: 6fa53202ce676297de24873c886443b2759bfd8a
                Found module libmount.so.1 with build-id: eeb33f2b4b9c3eb0a29575eb9932ef08663bd836
                Found module libz.so.1 with build-id: 30840b79ac329ecbf1dec0bb60180eed256d319f
                Found module libwayland-client.so.0 with build-id: a85980f4efa33fa5cadfbf257349fef99d499427
                Found module libwayland-egl.so.1 with build-id: e13dfac5961e8fb58c54984fe8110a73c2f5ef99
                Found module libwayland-cursor.so.0 with build-id: abcd1ab467757354ac36fd0938b82d47d7aebe1f
                Found module libxkbcommon.so.0 with build-id: a4b17d939092101dc8f6b2a1d70eaf1fddb2dd51
                Found module libXdamage.so.1 with build-id: 8358b7625700dc247fa21fb4304cba877a28bb04
                Found module libXcomposite.so.1 with build-id: 2c84db5342304ba1a76db7dd9b7a3bfaa8a716ce
                Found module libXcursor.so.1 with build-id: d936a5db46d8babb0f2cc490df36b6b18a16d8aa
                Found module libXinerama.so.1 with build-id: 9823bebfa26a681265db4aeb09abf44deec38401
                Found module libharfbuzz.so.0 with build-id: 3b9c495c079286b8d1f55d0937a0a771593eb7e6
                Found module libpango-1.0.so.0 with build-id: 42c8896c53d9d22dc73ba7a78b326d61f34e4442
                Found module libpangoft2-1.0.so.0 with build-id: fc7f13d8298f5e10fb1acbaa5472ec8b6fbf2bd9
                Found module libm.so.6 with build-id: a88ef0199bd5e742ebd0c359edf5cb2be0ec08b5
                Found module libfribidi.so.0 with build-id: 6e075a666e1da8ffdb948d734e75d82b1b6dc0fb
                Found module libepoxy.so.0 with build-id: 5ea53a2b100e4b044eee19d5222881a724abf046
                Found module libatk-bridge-2.0.so.0 with build-id: 7e8009077fbdcd7bf094c51bf78742b96f216d73
                Found module libcairo.so.2 with build-id: 60a39c3684e41370bd0a59ed1ecbdccf47e30069
                Found module libcairo-gobject.so.2 with build-id: 71b5bd37d77ea1862d2ed00e9f6ead482f307db8
                Found module libXfixes.so.3 with build-id: a9c550a40b8154a3b4b5e2ac182bb50c013c3f18
                Found module libpangocairo-1.0.so.0 with build-id: 65987e60b791e0eb6231575b8d5cfd33a6379b22
                Found module libgmodule-2.0.so.0 with build-id: 8b369a368c3070d179ddf64724ffc229c3f214b5
                Found module libuuid.so.1 with build-id: 64c0d0cb22fa2bdeca075a0c0418ba5ff314b220
                Found module libexpat.so.1 with build-id: d212d1f61d04a1e60fccad1a8c118428cfd9be42
                Found module libfreetype.so.6 with build-id: bc6c65a19e6f75fea5e74a7fd6c0b91182e1a8b0
                Found module libXext.so.6 with build-id: 9fb1880e02dfa11a8c39cd1a170109de08302059
                Found module libxkbfile.so.1 with build-id: b585f533dd10bd8c043f887705d4e45828baf206
                Found module libxml2.so.2 with build-id: 1cf4a22fbe15a77baca28e9c824592b8b5d852ff
                Found module libstartup-notification-1.so.0 with build-id: 1f2a87bcfb3b3a592bc43f2f9b65eca6b0764cea
                Found module libICE.so.6 with build-id: cf39da2f7c723f976c6e676704e218513e2b0b2b
                Found module libSM.so.6 with build-id: 6b32192c8a8870a8fe04403f537e806da93a1dd8
                Found module libgdk_pixbuf-2.0.so.0 with build-id: 374b383e3b68b5d8b552519094129f401596e502
                Found module libatk-1.0.so.0 with build-id: b93088667fbd06f6b72d273403d352e7c0554698
                Found module libc.so.6 with build-id: c289da5071a3399de893d2af81d6a30c62646e1e
                Found module libglib-2.0.so.0 with build-id: c74e800dfd5f72649d673b44292f4a817e45150b
                Found module libgobject-2.0.so.0 with build-id: 7c47809b4e688382aab4127a2e07496450c5e6b0
                Found module libupower-glib.so.3 with build-id: 480bb85a72a85c810228afed92f8084f66023c76
                Found module libXrandr.so.2 with build-id: 069f930a2b41f3908a1a92b1a51c38bd13a559e2
                Found module libX11.so.6 with build-id: 37a5d7bbb78e3a99ea8376a7c80ea0c62fe06494
                Found module libgio-2.0.so.0 with build-id: 07bd46a1bb58e321e6aabc67135d054e6b78069d
                Found module libxfconf-0.so.3 with build-id: 5624e72c364737c77d8fc0dcb376f498406f74d4
                Found module libgdk-3.so.0 with build-id: 97b768ef80858a79741be2492754d948989e63c6
                Found module libgtk-3.so.0 with build-id: 9a340345f5e200f42140f3cb4bacb407e91843f8
                Found module libfontconfig.so.1 with build-id: 0bb435fdd5ec37178e14ea03bb36f779a4b72a94
                Found module libnotify.so.4 with build-id: 9f17eb75ce0087dc0e9e2049eeb47d37883006e3
                Found module libXi.so.6 with build-id: 8ff5a3ac871a90fd9d0a7917c61f748a41c6b5ee
                Found module libxklavier.so.16 with build-id: a581072418d786fb4a1d160ee7143bbd977025e7
                Found module libxfce4util.so.7 with build-id: 0579e1252fc10141c3866b50484cc3c38595c521
                Found module libxfce4ui-2.so.0 with build-id: 5316287651399d64fc1da05f05ca406f1f118ab1
                Found module libxfce4kbd-private-3.so.0 with build-id: 03f0becce2a73bf24d0271c9be07bc4da8b69293
                Found module xfsettingsd with build-id: 178ee7c1f000458f2288e05468151f6d57688d07
                Stack trace of thread 159380:
                #0  0x00007f8abfca7167 g_log_writer_default (libglib-2.0.so.0 + 0x61167)
                #1  0x00007f8abfca2cb3 g_log_structured_array (libglib-2.0.so.0 + 0x5ccb3)
                #2  0x00007f8abfca2eb3 g_log_structured_standard (libglib-2.0.so.0 + 0x5ceb3)
                #3  0x0000557a939b4fcc n/a (xfsettingsd + 0x9fcc)
                #4  0x00007f8abfa29d90 __libc_start_call_main (libc.so.6 + 0x29d90)
                #5  0x00007f8abfa29e40 __libc_start_main_impl (libc.so.6 + 0x29e40)
                #6  0x0000557a939b5005 n/a (xfsettingsd + 0xa005)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 159380]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `xfsettingsd --display :0.0 --sm-client-id 2eb19bff7-6862-4932-b375-c24234be40e3'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f8abfca7167 in g_log_writer_default () from /lib/x86_64-linux-gnu/libglib-2.0.so.0

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 159380]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `xfsettingsd --display :0.0 --sm-client-id 2eb19bff7-6862-4932-b375-c24234be40e3'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f8abfca7167 in g_log_writer_default () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#0  0x00007f8abfca7167 in g_log_writer_default () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f8abfca2cb3 in g_log_structured_array () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f8abfca2eb3 in g_log_structured_standard () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x0000557a939b4fcc in  ()
#4  0x00007f8abfa29d90 in __libc_start_call_main (main=main@entry=0x557a939b4820, argc=argc@entry=5, argv=argv@entry=0x7fffeaa50338) at ../sysdeps/nptl/libc_start_call_main.h:58
#5  0x00007f8abfa29e40 in __libc_start_main_impl (main=0x557a939b4820, argc=5, argv=0x7fffeaa50338, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffeaa50328) at ../csu/libc-start.c:392
#6  0x0000557a939b5005 in  ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 159380]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `xfsettingsd --display :0.0 --sm-client-id 2eb19bff7-6862-4932-b375-c24234be40e3'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f8abfca7167 in g_log_writer_default () from /lib/x86_64-linux-gnu/libglib-2.0.so.0

Thread 1 (Thread 0x7f8abca79a80 (LWP 159380)):
#0  0x00007f8abfca7167 in g_log_writer_default () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f8abfca2cb3 in g_log_structured_array () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f8abfca2eb3 in g_log_structured_standard () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x0000557a939b4fcc in  ()
#4  0x00007f8abfa29d90 in __libc_start_call_main (main=main@entry=0x557a939b4820, argc=argc@entry=5, argv=argv@entry=0x7fffeaa50338) at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 842875690368929214, 140737130070840, 93984950798368, 93984950891032, 140233915822144, -842828767709983298, -817682897279218242}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#5  0x00007f8abfa29e40 in __libc_start_main_impl (main=0x557a939b4820, argc=5, argv=0x7fffeaa50338, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffeaa50328) at ../csu/libc-start.c:392
#6  0x0000557a939b5005 in  ()
#0  0x00007f8abfca7167 in g_log_writer_default () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f8abfca2cb3 in g_log_structured_array () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f8abfca2eb3 in g_log_structured_standard () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x0000557a939b4fcc in  ()
#4  0x00007f8abfa29d90 in __libc_start_call_main (main=main@entry=0x557a939b4820, argc=argc@entry=5, argv=argv@entry=0x7fffeaa50338) at ../sysdeps/nptl/libc_start_call_main.h:58
#5  0x00007f8abfa29e40 in __libc_start_main_impl (main=0x557a939b4820, argc=5, argv=0x7fffeaa50338, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffeaa50328) at ../csu/libc-start.c:392
#6  0x0000557a939b5005 in  ()
